language: node_js
node_js:
- '5'
install:
- npm install
script:
- NODE_ENV=production webpack -p
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Zbpmn0KTdH58Fx6FeJwRXhppdvJCn9mBOxPysomBbn1H6sPViFdKOkmqqOfRRr6OwcsWg/tzbv1mcbghqIr/5aWm8NnnUkpb9Y0C7eofxhM/RqKNnmnnmaT9hpRwwgfMujwRxMmB189vAUhRANKTfiEXnbFk99yxKZ0vkmy7gM8UvB08JJJijVoL5/rqk724ic8r9etcgPMOMhv2eOMpZx3T7zsSS5MK1w9k4s3mngMmIYs/6IEuEc6ETjnLg1RDEVtTZYw/iPccUi5vSJj5IohuQUXVG7bSqstMNyvq/ckAOghwPGbvrOKYSosIHzCK4LUzIdfQ/mT1Z69+mcqAUYpGCY267TRsfX2XObxz+Qtd75QUE8n03qJBjWmRArxPX6NoFX8sJ5FnlswWbAgTeyM0sC6CEsE0ul2uqk89KQegO2zOGONaWzJbmlzQIOe322WAtHCA2Ep/+MWgIOitIliIkQy5GIegV6ew1OBvgo/rESDuAWwF/av6Vgzl/m1bT385HSPSOjQWnDZHqeU8n1FlY+bNRKso0Wj5OCakan1LF6/238UFSfo3Gq/OpWmhWM0mxik/7rpbH3Co3jzSPrOnqPdDFUNQb1xTGg5x57z2O8uJizYqMEigu0vtd4WNilW5+Suo4QBF/Z9GUt3zCqgvZa4U5NcBf74ZPXCJhno=
  app:
      master: gomocha
  on:
    repo: amituuush/gomocha
